import type { Metadata } from "next";
import "./globals.css";
import Nav from "@/components/Nav/Nav";
import { domAnimation, LazyMotion } from "framer-motion";

export const metadata: Metadata = {
  title: "",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <LazyMotion features={domAnimation}>
        <body className="bg-light-grey text-black text-base selection:bg-black selection:text-[#ffffff]">
          {/* <Nav /> */}
          {children}
        </body>
      </LazyMotion>
    </html>
  );
}
