import type { Metadata } from "next";
import "./globals.css";
import Nav from "@/components/Nav/Nav";

export const metadata: Metadata = {
  title: "",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-light-grey text-black text-base selection:bg-black">
        <Nav />
        {children}
      </body>
    </html>
  );
}
