import gsap from "gsap";

export type Easing =
  | "power0"
  | "power1"
  | "power1.in"
  | "power1.out"
  | "power1.inOut"
  | "power2"
  | "power2.in"
  | "power2.out"
  | "power2.inOut"
  | "power3"
  | "power3.in"
  | "power3.out"
  | "power3.inOut"
  | "power4"
  | "power4.in"
  | "power4.out"
  | "power4.inOut"
  | "back"
  | "back.in"
  | "back.out"
  | "back.inOut"
  | "elastic"
  | "elastic.in"
  | "elastic.out"
  | "elastic.inOut"
  | "bounce"
  | "bounce.in"
  | "bounce.out"
  | "bounce.inOut"
  | "rough"
  | "rough.in"
  | "rough.out"
  | "rough.inOut"
  | "slow"
  | "slow.in"
  | "slow.out"
  | "slow.inOut"
  | "steps"
  | "steps.in"
  | "steps.out"
  | "steps.inOut"
  | "circ"
  | "circ.in"
  | "circ.out"
  | "circ.inOut"
  | "expo"
  | "expo.in"
  | "expo.out"
  | "expo.inOut"
  | "sine"
  | "sine.in"
  | "sine.out"
  | "sine.inOut"
  | "none"
  | "linear";

function parseEasing(easing: Easing) {
  return gsap.parseEase(easing);
}

export default parseEasing;
